---
- name: Pull latest changes from origin/master
  git:
    repo: "{{ dotfiles_dir }}"
    dest: "{{ dotfiles_dir }}"
    version: master
    update: yes
  register: git_result

- name: Show git pull result
  debug:
    msg: "Git status: {{ 'Updated' if git_result.changed else 'Already up to date' }}"
